//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_biga_H
#define METASPRITE_biga_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo biga;

#endif
