//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_compass_H
#define METASPRITE_compass_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo compass;

#endif
