//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fire_H
#define METASPRITE_fire_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo fire;

#endif
