//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_horse8frames_H
#define METASPRITE_horse8frames_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo horse8frames;

#endif
