//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_item_H
#define METASPRITE_item_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo item;

#endif
