//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_step_H
#define METASPRITE_step_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo step;

#endif
