/*

 AREAROMET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __arearomet_h_INCLUDE
#define __arearomet_h_INCLUDE

/* Bank of tiles. */
#define arearometBank 0

/* Super Gameboy palette 0 */
#define arearometSGBPal0c0 0
#define arearometSGBPal0c1 0
#define arearometSGBPal0c2 0
#define arearometSGBPal0c3 0

/* Super Gameboy palette 1 */
#define arearometSGBPal1c0 6076
#define arearometSGBPal1c1 8935
#define arearometSGBPal1c2 6596
#define arearometSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define arearometSGBPal2c0 6076
#define arearometSGBPal2c1 8935
#define arearometSGBPal2c2 6596
#define arearometSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define arearometSGBPal3c0 6076
#define arearometSGBPal3c1 8935
#define arearometSGBPal3c2 6596
#define arearometSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define arearometCGBPal0c0 31504
#define arearometCGBPal0c1 15326
#define arearometCGBPal0c2 652
#define arearometCGBPal0c3 119

/* Gameboy Color palette 1 */
#define arearometCGBPal1c0 6076
#define arearometCGBPal1c1 8935
#define arearometCGBPal1c2 6596
#define arearometCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define arearometCGBPal2c0 6076
#define arearometCGBPal2c1 8935
#define arearometCGBPal2c2 6596
#define arearometCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define arearometCGBPal3c0 6076
#define arearometCGBPal3c1 8935
#define arearometCGBPal3c2 6596
#define arearometCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define arearometCGBPal4c0 6076
#define arearometCGBPal4c1 8935
#define arearometCGBPal4c2 6596
#define arearometCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define arearometCGBPal5c0 6076
#define arearometCGBPal5c1 8935
#define arearometCGBPal5c2 6596
#define arearometCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define arearometCGBPal6c0 6076
#define arearometCGBPal6c1 8935
#define arearometCGBPal6c2 6596
#define arearometCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define arearometCGBPal7c0 6076
#define arearometCGBPal7c1 8935
#define arearometCGBPal7c2 6596
#define arearometCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char arearomet[];

#endif

/* End of AREAROMET.H */
