/*

 AREAEGYPTT01.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 95

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __areaegyptt01_h_INCLUDE
#define __areaegyptt01_h_INCLUDE

/* Bank of tiles. */
#define areaegyptt01Bank 0

/* Super Gameboy palette 0 */
#define areaegyptt01SGBPal0c0 0
#define areaegyptt01SGBPal0c1 0
#define areaegyptt01SGBPal0c2 0
#define areaegyptt01SGBPal0c3 0

/* Super Gameboy palette 1 */
#define areaegyptt01SGBPal1c0 6076
#define areaegyptt01SGBPal1c1 8935
#define areaegyptt01SGBPal1c2 6596
#define areaegyptt01SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define areaegyptt01SGBPal2c0 6076
#define areaegyptt01SGBPal2c1 8935
#define areaegyptt01SGBPal2c2 6596
#define areaegyptt01SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define areaegyptt01SGBPal3c0 6076
#define areaegyptt01SGBPal3c1 8935
#define areaegyptt01SGBPal3c2 6596
#define areaegyptt01SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define areaegyptt01CGBPal0c0 31707
#define areaegyptt01CGBPal0c1 15262
#define areaegyptt01CGBPal0c2 31749
#define areaegyptt01CGBPal0c3 0

/* Gameboy Color palette 1 */
#define areaegyptt01CGBPal1c0 6076
#define areaegyptt01CGBPal1c1 8935
#define areaegyptt01CGBPal1c2 6596
#define areaegyptt01CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define areaegyptt01CGBPal2c0 6076
#define areaegyptt01CGBPal2c1 8935
#define areaegyptt01CGBPal2c2 6596
#define areaegyptt01CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define areaegyptt01CGBPal3c0 6076
#define areaegyptt01CGBPal3c1 8935
#define areaegyptt01CGBPal3c2 6596
#define areaegyptt01CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define areaegyptt01CGBPal4c0 6076
#define areaegyptt01CGBPal4c1 8935
#define areaegyptt01CGBPal4c2 6596
#define areaegyptt01CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define areaegyptt01CGBPal5c0 6076
#define areaegyptt01CGBPal5c1 8935
#define areaegyptt01CGBPal5c2 6596
#define areaegyptt01CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define areaegyptt01CGBPal6c0 6076
#define areaegyptt01CGBPal6c1 8935
#define areaegyptt01CGBPal6c2 6596
#define areaegyptt01CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define areaegyptt01CGBPal7c0 6076
#define areaegyptt01CGBPal7c1 8935
#define areaegyptt01CGBPal7c2 6596
#define areaegyptt01CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char areaegyptt01[];

#endif

/* End of AREAEGYPTT01.H */
