/*

 AREADESERTT02.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 95

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __areadesertt02_h_INCLUDE
#define __areadesertt02_h_INCLUDE

/* Bank of tiles. */
#define areadesertt02Bank 0

/* Super Gameboy palette 0 */
#define areadesertt02SGBPal0c0 0
#define areadesertt02SGBPal0c1 0
#define areadesertt02SGBPal0c2 0
#define areadesertt02SGBPal0c3 0

/* Super Gameboy palette 1 */
#define areadesertt02SGBPal1c0 6076
#define areadesertt02SGBPal1c1 8935
#define areadesertt02SGBPal1c2 6596
#define areadesertt02SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define areadesertt02SGBPal2c0 6076
#define areadesertt02SGBPal2c1 8935
#define areadesertt02SGBPal2c2 6596
#define areadesertt02SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define areadesertt02SGBPal3c0 6076
#define areadesertt02SGBPal3c1 8935
#define areadesertt02SGBPal3c2 6596
#define areadesertt02SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define areadesertt02CGBPal0c0 31569
#define areadesertt02CGBPal0c1 20382
#define areadesertt02CGBPal0c2 223
#define areadesertt02CGBPal0c3 1360

/* Gameboy Color palette 1 */
#define areadesertt02CGBPal1c0 6076
#define areadesertt02CGBPal1c1 8935
#define areadesertt02CGBPal1c2 6596
#define areadesertt02CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define areadesertt02CGBPal2c0 6076
#define areadesertt02CGBPal2c1 8935
#define areadesertt02CGBPal2c2 6596
#define areadesertt02CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define areadesertt02CGBPal3c0 6076
#define areadesertt02CGBPal3c1 8935
#define areadesertt02CGBPal3c2 6596
#define areadesertt02CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define areadesertt02CGBPal4c0 6076
#define areadesertt02CGBPal4c1 8935
#define areadesertt02CGBPal4c2 6596
#define areadesertt02CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define areadesertt02CGBPal5c0 6076
#define areadesertt02CGBPal5c1 8935
#define areadesertt02CGBPal5c2 6596
#define areadesertt02CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define areadesertt02CGBPal6c0 6076
#define areadesertt02CGBPal6c1 8935
#define areadesertt02CGBPal6c2 6596
#define areadesertt02CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define areadesertt02CGBPal7c0 6076
#define areadesertt02CGBPal7c1 8935
#define areadesertt02CGBPal7c2 6596
#define areadesertt02CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char areadesertt02[];

#endif

/* End of AREADESERTT02.H */
