/*

 AREAROMET99.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __arearomet99_h_INCLUDE
#define __arearomet99_h_INCLUDE

/* Bank of tiles. */
#define arearomet99Bank 0

/* Super Gameboy palette 0 */
#define arearomet99SGBPal0c0 0
#define arearomet99SGBPal0c1 0
#define arearomet99SGBPal0c2 0
#define arearomet99SGBPal0c3 0

/* Super Gameboy palette 1 */
#define arearomet99SGBPal1c0 6076
#define arearomet99SGBPal1c1 8935
#define arearomet99SGBPal1c2 6596
#define arearomet99SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define arearomet99SGBPal2c0 6076
#define arearomet99SGBPal2c1 8935
#define arearomet99SGBPal2c2 6596
#define arearomet99SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define arearomet99SGBPal3c0 6076
#define arearomet99SGBPal3c1 8935
#define arearomet99SGBPal3c2 6596
#define arearomet99SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define arearomet99CGBPal0c0 31504
#define arearomet99CGBPal0c1 15326
#define arearomet99CGBPal0c2 652
#define arearomet99CGBPal0c3 119

/* Gameboy Color palette 1 */
#define arearomet99CGBPal1c0 6076
#define arearomet99CGBPal1c1 8935
#define arearomet99CGBPal1c2 6596
#define arearomet99CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define arearomet99CGBPal2c0 6076
#define arearomet99CGBPal2c1 8935
#define arearomet99CGBPal2c2 6596
#define arearomet99CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define arearomet99CGBPal3c0 6076
#define arearomet99CGBPal3c1 8935
#define arearomet99CGBPal3c2 6596
#define arearomet99CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define arearomet99CGBPal4c0 6076
#define arearomet99CGBPal4c1 8935
#define arearomet99CGBPal4c2 6596
#define arearomet99CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define arearomet99CGBPal5c0 6076
#define arearomet99CGBPal5c1 8935
#define arearomet99CGBPal5c2 6596
#define arearomet99CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define arearomet99CGBPal6c0 6076
#define arearomet99CGBPal6c1 8935
#define arearomet99CGBPal6c2 6596
#define arearomet99CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define arearomet99CGBPal7c0 6076
#define arearomet99CGBPal7c1 8935
#define arearomet99CGBPal7c2 6596
#define arearomet99CGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char arearomet99[];

#endif

/* End of AREAROMET99.H */
