/*

 AREADESERTT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 95

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __areadesertt_h_INCLUDE
#define __areadesertt_h_INCLUDE

/* Bank of tiles. */
#define areadeserttBank 0

/* Super Gameboy palette 0 */
#define areadeserttSGBPal0c0 0
#define areadeserttSGBPal0c1 0
#define areadeserttSGBPal0c2 0
#define areadeserttSGBPal0c3 0

/* Super Gameboy palette 1 */
#define areadeserttSGBPal1c0 6076
#define areadeserttSGBPal1c1 8935
#define areadeserttSGBPal1c2 6596
#define areadeserttSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define areadeserttSGBPal2c0 6076
#define areadeserttSGBPal2c1 8935
#define areadeserttSGBPal2c2 6596
#define areadeserttSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define areadeserttSGBPal3c0 6076
#define areadeserttSGBPal3c1 8935
#define areadeserttSGBPal3c2 6596
#define areadeserttSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define areadeserttCGBPal0c0 31569
#define areadeserttCGBPal0c1 20382
#define areadeserttCGBPal0c2 223
#define areadeserttCGBPal0c3 1360

/* Gameboy Color palette 1 */
#define areadeserttCGBPal1c0 6076
#define areadeserttCGBPal1c1 8935
#define areadeserttCGBPal1c2 6596
#define areadeserttCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define areadeserttCGBPal2c0 6076
#define areadeserttCGBPal2c1 8935
#define areadeserttCGBPal2c2 6596
#define areadeserttCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define areadeserttCGBPal3c0 6076
#define areadeserttCGBPal3c1 8935
#define areadeserttCGBPal3c2 6596
#define areadeserttCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define areadeserttCGBPal4c0 6076
#define areadeserttCGBPal4c1 8935
#define areadeserttCGBPal4c2 6596
#define areadeserttCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define areadeserttCGBPal5c0 6076
#define areadeserttCGBPal5c1 8935
#define areadeserttCGBPal5c2 6596
#define areadeserttCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define areadeserttCGBPal6c0 6076
#define areadeserttCGBPal6c1 8935
#define areadeserttCGBPal6c2 6596
#define areadeserttCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define areadeserttCGBPal7c0 6076
#define areadeserttCGBPal7c1 8935
#define areadeserttCGBPal7c2 6596
#define areadeserttCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char areadesertt[];

#endif

/* End of AREADESERTT.H */
