/*

 BUTTONMAPT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 79

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __buttonmapt_h_INCLUDE
#define __buttonmapt_h_INCLUDE

/* Bank of tiles. */
#define buttonmaptBank 0

/* Super Gameboy palette 0 */
#define buttonmaptSGBPal0c0 0
#define buttonmaptSGBPal0c1 0
#define buttonmaptSGBPal0c2 0
#define buttonmaptSGBPal0c3 0

/* Super Gameboy palette 1 */
#define buttonmaptSGBPal1c0 6076
#define buttonmaptSGBPal1c1 8935
#define buttonmaptSGBPal1c2 6596
#define buttonmaptSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define buttonmaptSGBPal2c0 6076
#define buttonmaptSGBPal2c1 8935
#define buttonmaptSGBPal2c2 6596
#define buttonmaptSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define buttonmaptSGBPal3c0 6076
#define buttonmaptSGBPal3c1 8935
#define buttonmaptSGBPal3c2 6596
#define buttonmaptSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define buttonmaptCGBPal0c0 32767
#define buttonmaptCGBPal0c1 9023
#define buttonmaptCGBPal0c2 127
#define buttonmaptCGBPal0c3 0

/* Gameboy Color palette 1 */
#define buttonmaptCGBPal1c0 6076
#define buttonmaptCGBPal1c1 8935
#define buttonmaptCGBPal1c2 6596
#define buttonmaptCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define buttonmaptCGBPal2c0 6076
#define buttonmaptCGBPal2c1 8935
#define buttonmaptCGBPal2c2 6596
#define buttonmaptCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define buttonmaptCGBPal3c0 6076
#define buttonmaptCGBPal3c1 8935
#define buttonmaptCGBPal3c2 6596
#define buttonmaptCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define buttonmaptCGBPal4c0 6076
#define buttonmaptCGBPal4c1 8935
#define buttonmaptCGBPal4c2 6596
#define buttonmaptCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define buttonmaptCGBPal5c0 6076
#define buttonmaptCGBPal5c1 8935
#define buttonmaptCGBPal5c2 6596
#define buttonmaptCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define buttonmaptCGBPal6c0 6076
#define buttonmaptCGBPal6c1 8935
#define buttonmaptCGBPal6c2 6596
#define buttonmaptCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define buttonmaptCGBPal7c0 6076
#define buttonmaptCGBPal7c1 8935
#define buttonmaptCGBPal7c2 6596
#define buttonmaptCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char buttonmapt[];

#endif

/* End of BUTTONMAPT.H */
