/*

 MAPALPST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapalpst_h_INCLUDE
#define __mapalpst_h_INCLUDE

/* Bank of tiles. */
#define mapalpstBank 0

/* Super Gameboy palette 0 */
#define mapalpstSGBPal0c0 0
#define mapalpstSGBPal0c1 0
#define mapalpstSGBPal0c2 0
#define mapalpstSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapalpstSGBPal1c0 6076
#define mapalpstSGBPal1c1 8935
#define mapalpstSGBPal1c2 6596
#define mapalpstSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapalpstSGBPal2c0 6076
#define mapalpstSGBPal2c1 8935
#define mapalpstSGBPal2c2 6596
#define mapalpstSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapalpstSGBPal3c0 6076
#define mapalpstSGBPal3c1 8935
#define mapalpstSGBPal3c2 6596
#define mapalpstSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapalpstCGBPal0c0 17240
#define mapalpstCGBPal0c1 11057
#define mapalpstCGBPal0c2 5509
#define mapalpstCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define mapalpstCGBPal1c0 6076
#define mapalpstCGBPal1c1 8935
#define mapalpstCGBPal1c2 6596
#define mapalpstCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapalpstCGBPal2c0 6076
#define mapalpstCGBPal2c1 8935
#define mapalpstCGBPal2c2 6596
#define mapalpstCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define mapalpstCGBPal3c0 6076
#define mapalpstCGBPal3c1 8935
#define mapalpstCGBPal3c2 6596
#define mapalpstCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mapalpstCGBPal4c0 6076
#define mapalpstCGBPal4c1 8935
#define mapalpstCGBPal4c2 6596
#define mapalpstCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapalpstCGBPal5c0 6076
#define mapalpstCGBPal5c1 8935
#define mapalpstCGBPal5c2 6596
#define mapalpstCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapalpstCGBPal6c0 6076
#define mapalpstCGBPal6c1 8935
#define mapalpstCGBPal6c2 6596
#define mapalpstCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapalpstCGBPal7c0 6076
#define mapalpstCGBPal7c1 8935
#define mapalpstCGBPal7c2 6596
#define mapalpstCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapalpst[];

#endif

/* End of MAPALPST.H */
