/*

 MAPDESERTT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapdesertt_h_INCLUDE
#define __mapdesertt_h_INCLUDE

/* Bank of tiles. */
#define mapdeserttBank 0

/* Super Gameboy palette 0 */
#define mapdeserttSGBPal0c0 0
#define mapdeserttSGBPal0c1 0
#define mapdeserttSGBPal0c2 0
#define mapdeserttSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapdeserttSGBPal1c0 6076
#define mapdeserttSGBPal1c1 8935
#define mapdeserttSGBPal1c2 6596
#define mapdeserttSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapdeserttSGBPal2c0 6076
#define mapdeserttSGBPal2c1 8935
#define mapdeserttSGBPal2c2 6596
#define mapdeserttSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapdeserttSGBPal3c0 6076
#define mapdeserttSGBPal3c1 8935
#define mapdeserttSGBPal3c2 6596
#define mapdeserttSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapdeserttCGBPal0c0 24510
#define mapdeserttCGBPal0c1 32589
#define mapdeserttCGBPal0c2 764
#define mapdeserttCGBPal0c3 1262

/* Gameboy Color palette 1 */
#define mapdeserttCGBPal1c0 24510
#define mapdeserttCGBPal1c1 8935
#define mapdeserttCGBPal1c2 6596
#define mapdeserttCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapdeserttCGBPal2c0 24510
#define mapdeserttCGBPal2c1 471
#define mapdeserttCGBPal2c2 1358
#define mapdeserttCGBPal2c3 0

/* Gameboy Color palette 3 */
#define mapdeserttCGBPal3c0 24510
#define mapdeserttCGBPal3c1 32617
#define mapdeserttCGBPal3c2 28992
#define mapdeserttCGBPal3c3 19776

/* Gameboy Color palette 4 */
#define mapdeserttCGBPal4c0 6076
#define mapdeserttCGBPal4c1 8935
#define mapdeserttCGBPal4c2 6596
#define mapdeserttCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapdeserttCGBPal5c0 6076
#define mapdeserttCGBPal5c1 8935
#define mapdeserttCGBPal5c2 6596
#define mapdeserttCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapdeserttCGBPal6c0 6076
#define mapdeserttCGBPal6c1 8935
#define mapdeserttCGBPal6c2 6596
#define mapdeserttCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapdeserttCGBPal7c0 6076
#define mapdeserttCGBPal7c1 8935
#define mapdeserttCGBPal7c2 6596
#define mapdeserttCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapdesertt[];

#endif

/* End of MAPDESERTT.H */
