/*

 MAPEGYPTTTNOFLAME.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapegyptttnoflame_h_INCLUDE
#define __mapegyptttnoflame_h_INCLUDE

/* Bank of tiles. */
#define mapegyptttnoflameBank 0

/* Super Gameboy palette 0 */
#define mapegyptttnoflameSGBPal0c0 0
#define mapegyptttnoflameSGBPal0c1 0
#define mapegyptttnoflameSGBPal0c2 0
#define mapegyptttnoflameSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapegyptttnoflameSGBPal1c0 6076
#define mapegyptttnoflameSGBPal1c1 8935
#define mapegyptttnoflameSGBPal1c2 6596
#define mapegyptttnoflameSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapegyptttnoflameSGBPal2c0 6076
#define mapegyptttnoflameSGBPal2c1 8935
#define mapegyptttnoflameSGBPal2c2 6596
#define mapegyptttnoflameSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapegyptttnoflameSGBPal3c0 6076
#define mapegyptttnoflameSGBPal3c1 8935
#define mapegyptttnoflameSGBPal3c2 6596
#define mapegyptttnoflameSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapegyptttnoflameCGBPal0c0 24510
#define mapegyptttnoflameCGBPal0c1 223
#define mapegyptttnoflameCGBPal0c2 183
#define mapegyptttnoflameCGBPal0c3 35

/* Gameboy Color palette 1 */
#define mapegyptttnoflameCGBPal1c0 24510
#define mapegyptttnoflameCGBPal1c1 8935
#define mapegyptttnoflameCGBPal1c2 6596
#define mapegyptttnoflameCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapegyptttnoflameCGBPal2c0 24510
#define mapegyptttnoflameCGBPal2c1 471
#define mapegyptttnoflameCGBPal2c2 1358
#define mapegyptttnoflameCGBPal2c3 0

/* Gameboy Color palette 3 */
#define mapegyptttnoflameCGBPal3c0 24510
#define mapegyptttnoflameCGBPal3c1 32617
#define mapegyptttnoflameCGBPal3c2 28992
#define mapegyptttnoflameCGBPal3c3 19776

/* Gameboy Color palette 4 */
#define mapegyptttnoflameCGBPal4c0 24510
#define mapegyptttnoflameCGBPal4c1 32589
#define mapegyptttnoflameCGBPal4c2 764
#define mapegyptttnoflameCGBPal4c3 1262

/* Gameboy Color palette 5 */
#define mapegyptttnoflameCGBPal5c0 6076
#define mapegyptttnoflameCGBPal5c1 8935
#define mapegyptttnoflameCGBPal5c2 6596
#define mapegyptttnoflameCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapegyptttnoflameCGBPal6c0 6076
#define mapegyptttnoflameCGBPal6c1 8935
#define mapegyptttnoflameCGBPal6c2 6596
#define mapegyptttnoflameCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapegyptttnoflameCGBPal7c0 6076
#define mapegyptttnoflameCGBPal7c1 8935
#define mapegyptttnoflameCGBPal7c2 6596
#define mapegyptttnoflameCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapegyptttnoflame[];

#endif

/* End of MAPEGYPTTTNOFLAME.H */
