/*

 MAPEGYPTT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapegyptt_h_INCLUDE
#define __mapegyptt_h_INCLUDE

/* Bank of tiles. */
#define mapegypttBank 0

/* Super Gameboy palette 0 */
#define mapegypttSGBPal0c0 0
#define mapegypttSGBPal0c1 0
#define mapegypttSGBPal0c2 0
#define mapegypttSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapegypttSGBPal1c0 6076
#define mapegypttSGBPal1c1 8935
#define mapegypttSGBPal1c2 6596
#define mapegypttSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapegypttSGBPal2c0 6076
#define mapegypttSGBPal2c1 8935
#define mapegypttSGBPal2c2 6596
#define mapegypttSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapegypttSGBPal3c0 6076
#define mapegypttSGBPal3c1 8935
#define mapegypttSGBPal3c2 6596
#define mapegypttSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapegypttCGBPal0c0 17240
#define mapegypttCGBPal0c1 11057
#define mapegypttCGBPal0c2 5509
#define mapegypttCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define mapegypttCGBPal1c0 6076
#define mapegypttCGBPal1c1 8935
#define mapegypttCGBPal1c2 6596
#define mapegypttCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapegypttCGBPal2c0 6076
#define mapegypttCGBPal2c1 8935
#define mapegypttCGBPal2c2 6596
#define mapegypttCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define mapegypttCGBPal3c0 6076
#define mapegypttCGBPal3c1 8935
#define mapegypttCGBPal3c2 6596
#define mapegypttCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mapegypttCGBPal4c0 6076
#define mapegypttCGBPal4c1 8935
#define mapegypttCGBPal4c2 6596
#define mapegypttCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapegypttCGBPal5c0 6076
#define mapegypttCGBPal5c1 8935
#define mapegypttCGBPal5c2 6596
#define mapegypttCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapegypttCGBPal6c0 6076
#define mapegypttCGBPal6c1 8935
#define mapegypttCGBPal6c2 6596
#define mapegypttCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapegypttCGBPal7c0 6076
#define mapegypttCGBPal7c1 8935
#define mapegypttCGBPal7c2 6596
#define mapegypttCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapegyptt[];

#endif

/* End of MAPEGYPTT.H */
