/*

 MAPGREECET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapgreecet_h_INCLUDE
#define __mapgreecet_h_INCLUDE

/* Bank of tiles. */
#define mapgreecetBank 0

/* Super Gameboy palette 0 */
#define mapgreecetSGBPal0c0 0
#define mapgreecetSGBPal0c1 0
#define mapgreecetSGBPal0c2 0
#define mapgreecetSGBPal0c3 0

/* Super Gameboy palette 1 */
#define mapgreecetSGBPal1c0 6076
#define mapgreecetSGBPal1c1 8935
#define mapgreecetSGBPal1c2 6596
#define mapgreecetSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define mapgreecetSGBPal2c0 6076
#define mapgreecetSGBPal2c1 8935
#define mapgreecetSGBPal2c2 6596
#define mapgreecetSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define mapgreecetSGBPal3c0 6076
#define mapgreecetSGBPal3c1 8935
#define mapgreecetSGBPal3c2 6596
#define mapgreecetSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define mapgreecetCGBPal0c0 17240
#define mapgreecetCGBPal0c1 11057
#define mapgreecetCGBPal0c2 5509
#define mapgreecetCGBPal0c3 1250

/* Gameboy Color palette 1 */
#define mapgreecetCGBPal1c0 6076
#define mapgreecetCGBPal1c1 8935
#define mapgreecetCGBPal1c2 6596
#define mapgreecetCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define mapgreecetCGBPal2c0 6076
#define mapgreecetCGBPal2c1 8935
#define mapgreecetCGBPal2c2 6596
#define mapgreecetCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define mapgreecetCGBPal3c0 6076
#define mapgreecetCGBPal3c1 8935
#define mapgreecetCGBPal3c2 6596
#define mapgreecetCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define mapgreecetCGBPal4c0 6076
#define mapgreecetCGBPal4c1 8935
#define mapgreecetCGBPal4c2 6596
#define mapgreecetCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define mapgreecetCGBPal5c0 6076
#define mapgreecetCGBPal5c1 8935
#define mapgreecetCGBPal5c2 6596
#define mapgreecetCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define mapgreecetCGBPal6c0 6076
#define mapgreecetCGBPal6c1 8935
#define mapgreecetCGBPal6c2 6596
#define mapgreecetCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define mapgreecetCGBPal7c0 6076
#define mapgreecetCGBPal7c1 8935
#define mapgreecetCGBPal7c2 6596
#define mapgreecetCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapgreecet[];

#endif

/* End of MAPGREECET.H */
