/*

 MAPROMET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mapromet_h_INCLUDE
#define __mapromet_h_INCLUDE

/* Bank of tiles. */
#define maprometBank 0

/* Super Gameboy palette 0 */
#define maprometSGBPal0c0 0
#define maprometSGBPal0c1 0
#define maprometSGBPal0c2 0
#define maprometSGBPal0c3 0

/* Super Gameboy palette 1 */
#define maprometSGBPal1c0 6076
#define maprometSGBPal1c1 8935
#define maprometSGBPal1c2 6596
#define maprometSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define maprometSGBPal2c0 6076
#define maprometSGBPal2c1 8935
#define maprometSGBPal2c2 6596
#define maprometSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define maprometSGBPal3c0 6076
#define maprometSGBPal3c1 8935
#define maprometSGBPal3c2 6596
#define maprometSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define maprometCGBPal0c0 20414
#define maprometCGBPal0c1 15166
#define maprometCGBPal0c2 93
#define maprometCGBPal0c3 1421

/* Gameboy Color palette 1 */
#define maprometCGBPal1c0 20414
#define maprometCGBPal1c1 32617
#define maprometCGBPal1c2 28992
#define maprometCGBPal1c3 19776

/* Gameboy Color palette 2 */
#define maprometCGBPal2c0 20414
#define maprometCGBPal2c1 19026
#define maprometCGBPal2c2 93
#define maprometCGBPal2c3 1421

/* Gameboy Color palette 3 */
#define maprometCGBPal3c0 6076
#define maprometCGBPal3c1 8935
#define maprometCGBPal3c2 6596
#define maprometCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define maprometCGBPal4c0 6076
#define maprometCGBPal4c1 8935
#define maprometCGBPal4c2 6596
#define maprometCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define maprometCGBPal5c0 6076
#define maprometCGBPal5c1 8935
#define maprometCGBPal5c2 6596
#define maprometCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define maprometCGBPal6c0 6076
#define maprometCGBPal6c1 8935
#define maprometCGBPal6c2 6596
#define maprometCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define maprometCGBPal7c0 6076
#define maprometCGBPal7c1 8935
#define maprometCGBPal7c2 6596
#define maprometCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char mapromet[];

#endif

/* End of MAPROMET.H */
