/*

 TITLESCREENT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 175

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __titlescreent_h_INCLUDE
#define __titlescreent_h_INCLUDE

/* Bank of tiles. */
#define titlescreentBank 0

/* Super Gameboy palette 0 */
#define titlescreentSGBPal0c0 0
#define titlescreentSGBPal0c1 0
#define titlescreentSGBPal0c2 0
#define titlescreentSGBPal0c3 0

/* Super Gameboy palette 1 */
#define titlescreentSGBPal1c0 6076
#define titlescreentSGBPal1c1 8935
#define titlescreentSGBPal1c2 6596
#define titlescreentSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define titlescreentSGBPal2c0 6076
#define titlescreentSGBPal2c1 8935
#define titlescreentSGBPal2c2 6596
#define titlescreentSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define titlescreentSGBPal3c0 6076
#define titlescreentSGBPal3c1 8935
#define titlescreentSGBPal3c2 6596
#define titlescreentSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define titlescreentCGBPal0c0 21503
#define titlescreentCGBPal0c1 32767
#define titlescreentCGBPal0c2 703
#define titlescreentCGBPal0c3 2069

/* Gameboy Color palette 1 */
#define titlescreentCGBPal1c0 6076
#define titlescreentCGBPal1c1 8935
#define titlescreentCGBPal1c2 6596
#define titlescreentCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define titlescreentCGBPal2c0 6076
#define titlescreentCGBPal2c1 8935
#define titlescreentCGBPal2c2 6596
#define titlescreentCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define titlescreentCGBPal3c0 6076
#define titlescreentCGBPal3c1 8935
#define titlescreentCGBPal3c2 6596
#define titlescreentCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define titlescreentCGBPal4c0 6076
#define titlescreentCGBPal4c1 8935
#define titlescreentCGBPal4c2 6596
#define titlescreentCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define titlescreentCGBPal5c0 6076
#define titlescreentCGBPal5c1 8935
#define titlescreentCGBPal5c2 6596
#define titlescreentCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define titlescreentCGBPal6c0 6076
#define titlescreentCGBPal6c1 8935
#define titlescreentCGBPal6c2 6596
#define titlescreentCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define titlescreentCGBPal7c0 6076
#define titlescreentCGBPal7c1 8935
#define titlescreentCGBPal7c2 6596
#define titlescreentCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char titlescreent[];

#endif

/* End of TITLESCREENT.H */
