/*

 WORLDMAPT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __worldmapt_h_INCLUDE
#define __worldmapt_h_INCLUDE

/* Bank of tiles. */
#define worldmaptBank 0

/* Super Gameboy palette 0 */
#define worldmaptSGBPal0c0 0
#define worldmaptSGBPal0c1 0
#define worldmaptSGBPal0c2 0
#define worldmaptSGBPal0c3 0

/* Super Gameboy palette 1 */
#define worldmaptSGBPal1c0 6076
#define worldmaptSGBPal1c1 8935
#define worldmaptSGBPal1c2 6596
#define worldmaptSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define worldmaptSGBPal2c0 6076
#define worldmaptSGBPal2c1 8935
#define worldmaptSGBPal2c2 6596
#define worldmaptSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define worldmaptSGBPal3c0 6076
#define worldmaptSGBPal3c1 8935
#define worldmaptSGBPal3c2 6596
#define worldmaptSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define worldmaptCGBPal0c0 31504
#define worldmaptCGBPal0c1 15326
#define worldmaptCGBPal0c2 652
#define worldmaptCGBPal0c3 0

/* Gameboy Color palette 1 */
#define worldmaptCGBPal1c0 6076
#define worldmaptCGBPal1c1 8935
#define worldmaptCGBPal1c2 6596
#define worldmaptCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define worldmaptCGBPal2c0 6076
#define worldmaptCGBPal2c1 8935
#define worldmaptCGBPal2c2 6596
#define worldmaptCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define worldmaptCGBPal3c0 6076
#define worldmaptCGBPal3c1 8935
#define worldmaptCGBPal3c2 6596
#define worldmaptCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define worldmaptCGBPal4c0 6076
#define worldmaptCGBPal4c1 8935
#define worldmaptCGBPal4c2 6596
#define worldmaptCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define worldmaptCGBPal5c0 6076
#define worldmaptCGBPal5c1 8935
#define worldmaptCGBPal5c2 6596
#define worldmaptCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define worldmaptCGBPal6c0 6076
#define worldmaptCGBPal6c1 8935
#define worldmaptCGBPal6c2 6596
#define worldmaptCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define worldmaptCGBPal7c0 6076
#define worldmaptCGBPal7c1 8935
#define worldmaptCGBPal7c2 6596
#define worldmaptCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char worldmapt[];

#endif

/* End of WORLDMAPT.H */
