//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_output_H
#define METASPRITE_output_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define output_TILE_ORIGIN 0
#define output_TILE_W 8
#define output_TILE_H 16
#define output_WIDTH 64
#define output_HEIGHT 224
#define output_TILE_COUNT 166
#define output_PALETTE_COUNT 1
#define output_COLORS_PER_PALETTE 4
#define output_TOTAL_COLORS 4
#define output_PIVOT_X 32
#define output_PIVOT_Y 112
#define output_PIVOT_W 64
#define output_PIVOT_H 224

BANKREF_EXTERN(output)

extern const palette_color_t output_palettes[4];
extern const uint8_t output_tiles[2656];

extern const metasprite_t* const output_metasprites[1];

#endif
