#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(camera)

const palette_color_t camera_palettes[4] = {
	RGB8(255,255,255), RGB8(170,170,170), RGB8( 85, 85, 85), RGB8(  0,  0,  0)
	
};

const uint8_t camera_tiles[32] = {
	0xc3,0xc3,0x81,0x81,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x81,0x81,0xc3,0xc3,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t camera_metasprite0[] = {
	METASPR_TERM
};

const metasprite_t camera_metasprite1[] = {
	METASPR_ITEM(0, 0, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const camera_metasprites[2] = {
	camera_metasprite0, camera_metasprite1
};

#include "MetaSpriteInfo.h"
const struct MetaSpriteInfo camera = {
	8, //width
	16, //height
	2, //num tiles
	camera_tiles, //tiles
	1, //num palettes
	camera_palettes, //CGB palette
	2, //num sprites
	camera_metasprites, //metasprites
};
