//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_camera_H
#define METASPRITE_camera_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo camera;

#endif
