//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fantoccio_H
#define METASPRITE_fantoccio_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo fantoccio;

#endif
