//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_oldhorse_H
#define METASPRITE_oldhorse_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#include "MetaSpriteInfo.h"

extern const struct MetaSpriteInfo oldhorse;

#endif
