#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(step)

const palette_color_t step_palettes[4] = {
	RGB8(248,248,248), RGB8(240,216,152), RGB8(200, 88,  0), RGB8( 80, 40,  8)
	
};

const uint8_t step_tiles[32] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x06,0x06,0x06,0x06,
	0x60,0x60,0x60,0x60,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t step_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const step_metasprites[1] = {
	step_metasprite0
};

#include "MetaSpriteInfo.h"
const struct MetaSpriteInfo step = {
	8, //width
	16, //height
	2, //num tiles
	step_tiles, //tiles
	1, //num palettes
	step_palettes, //CGB palette
	1, //num sprites
	step_metasprites, //metasprites
};
